os: linux
dist: bionic
language: php
php:
  - 7.2
before_script:
  - mv `pwd` ../en
  - cd ..
  - git clone --depth=1 git://github.com/php/doc-base.git doc-base
script:
  - php doc-base/configure.php --enable-xml-details --disable-libxml-check --redirect-stderr-to-stdout --with-lang=en

