language: php
php:
  - 5.4
before_script:
  - mv `pwd` ../en
  - cd ..
  - git clone --depth=1 git://github.com/salathe/phpdoc-base.git doc-base
script:
  - php doc-base/configure.php --enable-force-dom-save --enable-xml-details --disable-libxml-check --redirect-stderr-to-stdout --with-lang=en

